# Generated by Django 3.2 on 2023-04-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Produto')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('images', models.ImageField(upload_to='photo/products', verbose_name='Imagem')),
                ('stock', models.IntegerField(verbose_name='Estoque')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Ultima Alteração')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('cor', 'cor'), ('tamanho', 'tamanho')], max_length=100, verbose_name='Variação do produto')),
                ('variation_value', models.CharField(max_length=100, verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
