# Generated by Django 3.2 on 2023-02-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'cor'), ('size', 'tamanho')], max_length=100, verbose_name='Variação do produto')),
                ('variation_value', models.CharField(max_length=100, verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
