# Generated by Django 3.2 on 2023-02-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Produto',
            new_name='product',
        ),
    ]
