# Generated by Django 3.2 on 2023-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_produto_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('cor', 'cor'), ('tamanho', 'tamanho')], max_length=100, verbose_name='Variação do produto'),
        ),
    ]
