# Generated by Django 3.2 on 2023-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Itens do Carrinho', 'verbose_name_plural': 'Itens de Todos os Carrinhos'},
        ),
    ]
