# Generated by Django 3.2 on 2023-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20230208_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('docCPF', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
