# Generated by Django 3.2 on 2023-03-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
