# Generated by Django 3.2 on 2023-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('city', models.CharField(default='-', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='-', max_length=100, verbose_name='Estado')),
                ('country_name', models.CharField(default='-', max_length=100, verbose_name='Pais')),
                ('codPostal', models.CharField(default='-', max_length=20, verbose_name='Cep')),
                ('last_access', models.DateTimeField(auto_now_add=True, verbose_name='Ùltimo')),
                ('num_visits', models.IntegerField(default=0, verbose_name='Visitas')),
            ],
            options={
                'verbose_name': 'Logal de acesso',
                'verbose_name_plural': 'Locais de acesso',
            },
        ),
    ]
