# Generated by Django 3.2 on 2023-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='docCNPJ',
            field=models.IntegerField(default=0, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='docCPF',
            field=models.IntegerField(default=0, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
