# Generated by Django 3.2 on 2023-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='observation',
            field=models.CharField(default='- sem observações - ', max_length=500),
        ),
    ]
