# Generated by Django 3.2 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deliveryaddress_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='observation',
            field=models.CharField(max_length=500),
        ),
    ]
