# Generated by Django 3.2 on 2023-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesslocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslocation',
            old_name='ip',
            new_name='ip_local',
        ),
        migrations.AddField(
            model_name='accesslocation',
            name='ip_public',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP'),
        ),
    ]
