# Generated by Django 3.2 on 2023-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_doccnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='docCPF',
            field=models.IntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
