# Generated by Django 3.2 on 2023-02-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_doccpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='docCNPJ',
            field=models.IntegerField(blank=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
