# Generated by Django 3.2 on 2023-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_doccnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='docCNPJ',
            field=models.IntegerField(default=0, unique=True, verbose_name='CNPJ'),
        ),
    ]
