# Generated by Django 3.2 on 2023-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accesslocation_ip_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslocation',
            name='city',
            field=models.CharField(default='NotFound', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='accesslocation',
            name='codPostal',
            field=models.CharField(default='NotFound', max_length=20, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='accesslocation',
            name='country_name',
            field=models.CharField(default='NotFound', max_length=100, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='accesslocation',
            name='ip_local',
            field=models.CharField(blank=True, default='NotFound', max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='accesslocation',
            name='ip_public',
            field=models.CharField(blank=True, default='NotFound', max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='accesslocation',
            name='state',
            field=models.CharField(default='NotFound', max_length=100, verbose_name='Estado'),
        ),
    ]
