# Generated by Django 3.2 on 2023-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230509_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslocation',
            name='last_access',
            field=models.DateTimeField(auto_now=True, verbose_name='Ùltimo'),
        ),
    ]
