# Generated by Django 3.2 on 2023-01-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/categories/', verbose_name='Upload da imagem'),
        ),
    ]
