# Generated by Django 3.2 on 2023-04-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Número do Pedido')),
                ('order_note', models.CharField(blank=True, max_length=100, verbose_name='Nota do Pedido')),
                ('order_total', models.FloatField(verbose_name='Total do pedido')),
                ('tax', models.FloatField(verbose_name='Taxa')),
                ('status', models.CharField(choices=[('New', 'Novo'), ('Accepted', 'Aceito'), ('Completed', 'Concluído'), ('Cancelled', 'Cancelado')], default='New', max_length=10, verbose_name='Status')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('is_ordered', models.BooleanField(default=True, verbose_name='Ordenado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('Endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryaddress')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compras',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Tipo do Pagamento')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='Valor Pago')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Pagamento')),
                ('Usuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField(verbose_name='Valor do produto')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordenado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado')),
                ('Pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('Usuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Variação', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation')),
            ],
            options={
                'verbose_name': 'Produto do pedido',
                'verbose_name_plural': 'Produtos do pedido',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='Pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='Usuário',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
