# Generated by Django 3.2 on 2023-03-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido de compra', 'verbose_name_plural': 'Pedidos de compras'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Produto da ordem', 'verbose_name_plural': 'Produtos da ordem'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='Endereço de Entrega',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='Pagamento',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='Usuário',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='payment',
            new_name='Pagamento',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='Pedido',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user',
            new_name='Usuário',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='Variação',
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=1, verbose_name='Taxa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=True, verbose_name='Ordenado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nota do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='Número do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(verbose_name='Total do pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Novo'), ('Accepted', 'Aceito'), ('Completed', 'Conclído'), ('Cancelled', 'Cancelado')], default='New', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Adicionado'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordenado'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(verbose_name='Valor do produto'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(max_length=100, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='Tipo do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
    ]
