# Generated by Django 3.2 on 2023-04-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Endereco',
            new_name='delivery_address',
        ),
    ]
