# Generated by Django 3.2 on 2023-03-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230324_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='Usuário',
        ),
    ]
