# Generated by Django 3.2 on 2023-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230427_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Pagamento',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Usuário',
            new_name='user',
        ),
    ]
