# Generated by Django 3.2 on 2023-03-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_user_payment_usuário'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Produto do pedido', 'verbose_name_plural': 'Produtos do pedido'},
        ),
    ]
