# Generated by Django 3.2 on 2023-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Novo'), ('Accepted', 'Aceito'), ('Completed', 'Concluído'), ('Cancelled', 'Cancelado')], default='Novo', max_length=10, verbose_name='Status'),
        ),
    ]
