# Generated by Django 3.2 on 2023-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='-', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='codPostal',
            field=models.CharField(default='-', max_length=20, verbose_name='Cep'),
        ),
        migrations.AddField(
            model_name='order',
            name='country_name',
            field=models.CharField(default='-', max_length=100, verbose_name='Pais'),
        ),
    ]
